/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Celestial Dawn Opal Ring',
    description: 'A breathtaking Australian fire opal set in a hand-sculpted 14k recycled yellow gold band, flanked by two tiny ethically-sourced brilliant diamonds. Every ring is hand-hammered to capture the organic texture of sea-swept sand.',
    category: 'Rings',
    price: 380,
    materials: ['14k Yellow Gold', 'Australian Opal', 'Diamond'],
    image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Opal',
    rating: 4.9,
    reviewsCount: 24,
    dimensions: 'Band width: 1.8mm; Focal stone: 6x4mm',
    stock: 5
  },
  {
    id: 'p2',
    name: 'Aether Raw Herkimer Diamond Pendant',
    description: 'A double-terminated, water-clear Herkimer Diamond quartz crystal suspended from a delicate 18-inch 14k gold-filled chain. Selected for its natural geometric facets, no two crystals are alike, reflecting light with pristine organic brilliance.',
    category: 'Necklaces',
    price: 165,
    materials: ['14k Gold-Filled', 'Herkimer Diamond Quartz'],
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Herkimer Diamond',
    rating: 4.8,
    reviewsCount: 42,
    dimensions: 'Chain: 18 inches; Crystal: ~12mm',
    stock: 8
  },
  {
    id: 'p3',
    name: 'Solstice Sunburst Hoop Earrings',
    description: 'Striking hand-stamped solid sterling silver hoops featuring radiating cosmic lines that evoke the midsummer sun. Oxidized gently and hand-polished to highlight the artisan engraving, creating a gorgeous vintage patina.',
    category: 'Earrings',
    price: 110,
    materials: ['Sterling Silver'],
    image: 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 19,
    dimensions: 'Diameter: 22mm; Wire thickness: 1mm',
    stock: 12
  },
  {
    id: 'p4',
    name: 'Gilded Nebula Hammered Cuff',
    description: 'A thick, substantial brass cuff meticulously hand-hammered with a stippled planetary texture, then triple-plated in heavy 18k gold. Its adjustable, organic design wraps around the wrist like a warm beam of celestial light.',
    category: 'Bracelets',
    price: 145,
    materials: ['18k Gold Plated Brass'],
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 31,
    dimensions: 'Width: 8mm; Adjustable circumference',
    stock: 7
  },
  {
    id: 'p5',
    name: 'Deep Forest Emerald Studs',
    description: 'Exquisite, raw-cut Zambian emeralds held tightly in rustic sterling silver claw settings. Hand-cast to preserve the emeralds\' natural matrix, celebrating the beautiful inner inclusions (called the "jardin") of each raw gemstone.',
    category: 'Earrings',
    price: 195,
    materials: ['Sterling Silver', 'Raw Emerald'],
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Emerald',
    rating: 5.0,
    reviewsCount: 15,
    dimensions: 'Stones: ~5mm studs',
    stock: 4
  },
  {
    id: 'p6',
    name: 'Lunar Eclipse Baroque Pearl Necklace',
    description: 'A glowing, irregularly-shaped freshwater baroque pearl suspended within a hand-forged sterling silver crescent moon. Features a gorgeous toggle clasp that can be worn in the front or back, combining modern symmetry with antique elegance.',
    category: 'Necklaces',
    price: 220,
    materials: ['Sterling Silver', 'Baroque Freshwater Pearl'],
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Pearl',
    rating: 4.8,
    reviewsCount: 28,
    dimensions: 'Chain: 16 inches; Pearl pendant: 18mm',
    stock: 6
  },
  {
    id: 'p7',
    name: 'Terrene Hand-Woven Jasper Bracelet',
    description: 'Earth-toned Picture Jasper beads and solid silver spacer elements, woven by hand onto premium waxed linen cord. Captures the shifting pigments of natural canyons, finished with an adjustable silver slip-bead.',
    category: 'Bracelets',
    price: 85,
    materials: ['Picture Jasper Beads', 'Sterling Silver Elements', 'Linen Cord'],
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Jasper',
    rating: 4.6,
    reviewsCount: 14,
    dimensions: 'Adjustable from 6 to 8.5 inches',
    stock: 15
  },
  {
    id: 'p8',
    name: 'Artemis Obsidian Signet Ring',
    description: 'A bold, hand-carved black volcanic obsidian gemstone shield inlaid securely into a micro-textured sterling silver signet frame. Named after the goddess of the wild, symbolising protection, focus, and natural elegance.',
    category: 'Rings',
    price: 250,
    materials: ['Sterling Silver', 'Black Obsidian'],
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Obsidian',
    rating: 4.9,
    reviewsCount: 37,
    dimensions: 'Signet face: 12x10mm; Ring sizes: US 6-10 available',
    stock: 9
  },
  {
    id: 'p9',
    name: 'Elysian Aquamarine Drop Pendant',
    description: 'A raw, icy-blue Brazilian aquamarine crystal suspended from an asymmetric, textured solid sterling silver twig bail. This specimen resembles a block of frozen glacial water reflecting a clear winter sky.',
    category: 'Necklaces',
    price: 180,
    materials: ['Sterling Silver', 'Raw Aquamarine'],
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Aquamarine',
    rating: 4.8,
    reviewsCount: 22,
    dimensions: 'Chain: 20 inches; Pendant length: 15mm',
    stock: 6
  },
  {
    id: 'p10',
    name: 'Solaria Hammered Gold Band',
    description: 'An ultra-thick, raw-hewn solid gold-filled band bearing deep, irregular forge marks reminiscent of volcanic ridges. Its surface is lightly hand-brushed for a soft, matte luster that ages with character.',
    category: 'Rings',
    price: 135,
    materials: ['14k Gold-Filled'],
    image: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 18,
    dimensions: 'Band width: 4.5mm; US sizes 5-9 available',
    stock: 8
  },
  {
    id: 'p11',
    name: 'Vesper Labradorite Talisman',
    description: 'A flashing labradorite cabochon set in an oxidized sterling silver shield pendant. When kissed by light, the stone flashes with electric blues and forest greens like the aurora borealis.',
    category: 'Necklaces',
    price: 210,
    materials: ['Sterling Silver', 'Spectrolite Labradorite'],
    image: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Labradorite',
    rating: 4.7,
    reviewsCount: 29,
    dimensions: 'Chain: 18 inches; Shield: 14x18mm',
    stock: 4
  },
  {
    id: 'p12',
    name: 'Aura Amethyst Raw Druzy Studs',
    description: 'Sparkling natural amethyst druzy specimens preserved in their crystal-cave form. Electrowon with heavy 18k yellow gold along the raw edges, offering a striking contrast of velvet purple and sparkling gold.',
    category: 'Earrings',
    price: 155,
    materials: ['18k Gold Plated Brass', 'Raw Amethyst Druzy'],
    image: 'https://images.unsplash.com/photo-1569397240129-c4303774afbe?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Amethyst',
    rating: 4.8,
    reviewsCount: 17,
    dimensions: 'Stud dimensions: ~7mm width',
    stock: 5
  },
  {
    id: 'p13',
    name: 'Chronos Textured Link Bracelet',
    description: 'Heavy, slow-forged rectangular brass links, individually beaten with custom tooling and silver-fused to create a distressed dual-tone antique finish. A chunky statement piece symbolizing the resilience of time.',
    category: 'Bracelets',
    price: 185,
    materials: ['Sterling Silver', 'Raw Brass'],
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 12,
    dimensions: 'Length: 7.5 inches; Link size: 12x6mm',
    stock: 7
  },
  {
    id: 'p14',
    name: 'Halcyon Moonstone Huggies',
    description: 'Charming mini hoops lined with delicate rainbow moonstones that reflect a soft, mystical blue glow at every angle. Hand-forged in sterling silver and polished to a bright, satin-like finish.',
    category: 'Earrings',
    price: 125,
    materials: ['Sterling Silver', 'Rainbow Moonstone'],
    image: 'https://images.unsplash.com/photo-1629224316810-9d8805b95e76?w=600&auto=format&fit=crop&q=80',
    gemstone: 'Moonstone',
    rating: 4.9,
    reviewsCount: 25,
    dimensions: 'Hoop inner diameter: 9mm; Stone count: 5 per hoop',
    stock: 10
  }
];
